spring.application.name=newsLetter
spring.profiles.active=local

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/newsLetter
spring.datasource.username=${DB_USERNAME:default}
spring.datasource.password=${DB_PASSWORD:default}

spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

spring.liquibase.enabled=false

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none